version: "3.9"
services:
  app:
    build: .
    container_name: rag_chatbox
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
